### ISSUE TITLE
homeassistant.components.meteo_france / 'str object' has no attribute 'weekday'

### ISSUE THREAD

**Issue by lboue** [NoahJust/home-assistant-config#1]
Bonjour,

Je rencontre un problème avec mon écran epaper-esp32. Les trigrammes des noms de jours ne s'affichent plus depuis plusieurs semaines. J'ai à la place "Not available". Par contre cela fonctionne correctement pour les températures .
Je pense que c'est liée à une MAJ de HA core. 

Voici mon fichier de conf qui contient le template : 
**/config/sensors.yaml**
```yaml
- platform: template
  sensors:
    # weather day correspond au jour de la semaine mis sur 3 lettres
    weather_day_1:
      value_template: "{{ ['LUN.', 'MAR.', 'MER.', 'JEU.', 'VEN.', 'SAM.', 'DIM.'][state_attr('weather.le_plessis_mace', 'forecast')[0].datetime.weekday()]}}"

    weather_day_2:
      value_template: "{{ ['LUN.', 'MAR.', 'MER.', 'JEU.', 'VEN.', 'SAM.', 'DIM.'][state_attr('weather.le_plessis_mace', 'forecast')[1].datetime.weekday()]}}"

    weather_day_3:
      value_template: "{{ ['LUN.', 'MAR.', 'MER.', 'JEU.', 'VEN.', 'SAM.', 'DIM.'][state_attr('weather.le_plessis_mace', 'forecast')[2].datetime.weekday()]}}"

    weather_day_4:
      value_template: "{{ ['LUN.', 'MAR.', 'MER.', 'JEU.', 'VEN.', 'SAM.', 'DIM.'][state_attr('weather.le_plessis_mace', 'forecast')[3].datetime.weekday()]}}"

    weather_day_5:
      value_template: "{{ ['LUN.', 'MAR.', 'MER.', 'JEU.', 'VEN.', 'SAM.', 'DIM.'][state_attr('weather.le_plessis_mace', 'forecast')[4].datetime.weekday()]}}"
                    
    # Day 1
    weather_temperature_1:
      value_template: "{{state_attr('weather.le_plessis_mace', 'forecast')[0].temperature}}"
    
    weather_templow_1:
      value_template: "{{state_attr('weather.le_plessis_mace', 'forecast')[0].templow}}"
    
    weather_condition_1:
      value_template: "{{state_attr('weather.le_plessis_mace', 'forecast')[0].condition}}"

    # Day 2
    weather_temperature_2:
      value_template: "{{state_attr('weather.le_plessis_mace', 'forecast')[1].temperature}}"
    
    weather_templow_2:
      value_template: "{{state_attr('weather.le_plessis_mace', 'forecast')[2].templow}}"
    
    weather_condition_2:
      value_template: "{{state_attr('weather.le_plessis_mace', 'forecast')[2].condition}}"

    # Day 3
    weather_temperature_3:
      value_template: "{{state_attr('weather.le_plessis_mace', 'forecast')[3].temperature}}"
    
    weather_templow_3:
      value_template: "{{state_attr('weather.le_plessis_mace', 'forecast')[3].templow}}"
    
    weather_condition_3:
      value_template: "{{state_attr('weather.le_plessis_mace', 'forecast')[3].condition}}"
      
    # Day 4
    weather_temperature_4:
      value_template: "{{state_attr('weather.le_plessis_mace', 'forecast')[4].temperature}}"
    
    weather_templow_4:
      value_template: "{{state_attr('weather.le_plessis_mace', 'forecast')[4].templow}}"
    
    weather_condition_4:
      value_template: "{{state_attr('weather.le_plessis_mace', 'forecast')[4].condition}}"
      
    # Day 5
    weather_temperature_5:
      value_template: "{{state_attr('weather.le_plessis_mace', 'forecast')[5].temperature}}"
    
    weather_templow_5:
      value_template: "{{state_attr('weather.le_plessis_mace', 'forecast')[5].templow}}"
    
    weather_condition_5:
      value_template: "{{state_attr('weather.le_plessis_mace', 'forecast')[5].condition}}"

```

Voici les logs DEBUG du module  weather
```java
homeassistant.exceptions.TemplateError: UndefinedError: 'str object' has no attribute 'weekday'
2023-10-13 15:23:51.921 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: 'str object' has no attribute 'weekday' when rendering '{{ ['LUN.', 'MAR.', 'MER.', 'JEU.', 'VEN.', 'SAM.', 'DIM.'][state_attr('weather.le_plessis_mace', 'forecast')[3].datetime.weekday()]}}'
2023-10-13 15:23:51.921 ERROR (MainThread) [homeassistant.components.template.template_entity] TemplateError('UndefinedError: 'str object' has no attribute 'weekday'') while processing template 'Template<template=({{ ['LUN.', 'MAR.', 'MER.', 'JEU.', 'VEN.', 'SAM.', 'DIM.'][state_attr('weather.le_plessis_mace', 'forecast')[3].datetime.weekday()]}}) renders=4>' for attribute '_attr_native_value' in entity 'sensor.weather_day_4'
2023-10-13 15:23:51.922 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: 'str object' has no attribute 'weekday' when rendering '{{ ['LUN.', 'MAR.', 'MER.', 'JEU.', 'VEN.', 'SAM.', 'DIM.'][state_attr('weather.le_plessis_mace', 'forecast')[4].datetime.weekday()]}}'
2023-10-13 15:23:51.923 ERROR (MainThread) [homeassistant.helpers.event] Error while processing template: Template<template=({{ ['LUN.', 'MAR.', 'MER.', 'JEU.', 'VEN.', 'SAM.', 'DIM.'][state_attr('weather.le_plessis_mace', 'forecast')[4].datetime.weekday()]}}) renders=2>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 568, in async_render
    render_result = _render_with_context(self.template, compiled, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2196, in _render_with_context
    return template.render(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
  File "/usr/local/lib/python3.11/site-packages/jinja2/sandbox.py", line 391, in call
    if not __self.is_safe_callable(__obj):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2542, in is_safe_callable
    return isinstance(obj, AllStates) or super().is_safe_callable(obj)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/jinja2/sandbox.py", line 275, in is_safe_callable
    getattr(obj, "unsafe_callable", False) or getattr(obj, "alters_data", False)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2231, in _fail_with_undefined_error
    raise ex
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2228, in _fail_with_undefined_error
    return super()._fail_with_undefined_error(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'str object' has no attribute 'weekday'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 694, in async_render_to_info
    render_info._result = self.async_render(
                          ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 570, in async_render
    raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: UndefinedError: 'str object' has no attribute 'weekday'
2023-10-13 15:23:51.930 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: 'str object' has no attribute 'weekday' when rendering '{{ ['LUN.', 'MAR.', 'MER.', 'JEU.', 'VEN.', 'SAM.', 'DIM.'][state_attr('weather.le_plessis_mace', 'forecast')[4].datetime.weekday()]}}'
2023-10-13 15:23:51.931 ERROR (MainThread) [homeassistant.components.template.template_entity] TemplateError('UndefinedError: 'str object' has no attribute 'weekday'') while processing template 'Template<template=({{ ['LUN.', 'MAR.', 'MER.', 'JEU.', 'VEN.', 'SAM.', 'DIM.'][state_attr('weather.le_plessis_mace', 'forecast')[4].datetime.weekday()]}}) renders=4>' for attribute '_attr_native_value' in entity 'sensor.weather_day_5'
2023-10-13 15:28:54.916 DEBUG (MainThread) [homeassistant.components.meteo_france] Weather alert for depatment 49 unloaded and released. It can be added now by another city
2023-10-13 15:28:54.931 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: None has no element 0 when rendering '{{ ['LUN.', 'MAR.', 'MER.', 'JEU.', 'VEN.', 'SAM.', 'DIM.'][state_attr('weather.le_plessis_mace', 'forecast')[0].datetime.weekday()]}}'
2023-10-13 15:28:54.932 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: None has no element 1 when rendering '{{ ['LUN.', 'MAR.', 'MER.', 'JEU.', 'VEN.', 'SAM.', 'DIM.'][state_attr('weather.le_plessis_mace', 'forecast')[1].datetime.weekday()]}}'
2023-10-13 15:28:54.932 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: None has no element 2 when rendering '{{ ['LUN.', 'MAR.', 'MER.', 'JEU.', 'VEN.', 'SAM.', 'DIM.'][state_attr('weather.le_plessis_mace', 'forecast')[2].datetime.weekday()]}}'
2023-10-13 15:28:54.937 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: None has no element 3 when rendering '{{ ['LUN.', 'MAR.', 'MER.', 'JEU.', 'VEN.', 'SAM.', 'DIM.'][state_attr('weather.le_plessis_mace', 'forecast')[3].datetime.weekday()]}}'
2023-10-13 15:28:54.937 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: None has no element 4 when rendering '{{ ['LUN.', 'MAR.', 'MER.', 'JEU.', 'VEN.', 'SAM.', 'DIM.'][state_attr('weather.le_plessis_mace', 'forecast')[4].datetime.weekday()]}}'
2023-10-13 15:28:54.938 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: None has no element 0 when rendering '{{state_attr('weather.le_plessis_mace', 'forecast')[0].temperature}}'
2023-10-13 15:28:54.938 ERROR (MainThread) [homeassistant.components.template.template_entity] TemplateError('UndefinedError: None has no element 0') while processing template 'Template<template=({{state_attr('weather.le_plessis_mace', 'forecast')[0].temperature}}) renders=6>' for attribute '_attr_native_value' in entity 'sensor.weather_temperature_1'
2023-10-13 15:28:54.939 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: None has no element 0 when rendering '{{state_attr('weather.le_plessis_mace', 'forecast')[0].templow}}'
2023-10-13 15:28:54.940 ERROR (MainThread) [homeassistant.components.template.template_entity] TemplateError('UndefinedError: None has no element 0') while processing template 'Template<template=({{state_attr('weather.le_plessis_mace', 'forecast')[0].templow}}) renders=6>' for attribute '_attr_native_value' in entity 'sensor.weather_templow_1'
2023-10-13 15:28:54.940 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: None has no element 0 when rendering '{{state_attr('weather.le_plessis_mace', 'forecast')[0].condition}}'
2023-10-13 15:28:54.940 ERROR (MainThread) [homeassistant.components.template.template_entity] TemplateError('UndefinedError: None has no element 0') while processing template 'Template<template=({{state_attr('weather.le_plessis_mace', 'forecast')[0].condition}}) renders=6>' for attribute '_attr_native_value' in entity 'sensor.weather_condition_1'
2023-10-13 15:28:54.941 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: None has no element 1 when rendering '{{state_attr('weather.le_plessis_mace', 'forecast')[1].temperature}}'
2023-10-13 15:28:54.944 ERROR (MainThread) [homeassistant.components.template.template_entity] TemplateError('UndefinedError: None has no element 1') while processing template 'Template<template=({{state_attr('weather.le_plessis_mace', 'forecast')[1].temperature}}) renders=6>' for attribute '_attr_native_value' in entity 'sensor.weather_temperature_2'
2023-10-13 15:28:54.945 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: None has no element 2 when rendering '{{state_attr('weather.le_plessis_mace', 'forecast')[2].templow}}'
2023-10-13 15:28:54.945 ERROR (MainThread) [homeassistant.components.template.template_entity] TemplateError('UndefinedError: None has no element 2') while processing template 'Template<template=({{state_attr('weather.le_plessis_mace', 'forecast')[2].templow}}) renders=6>' for attribute '_attr_native_value' in entity 'sensor.weather_templow_2'
2023-10-13 15:28:54.946 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: None has no element 2 when rendering '{{state_attr('weather.le_plessis_mace', 'forecast')[2].condition}}'
2023-10-13 15:28:54.946 ERROR (MainThread) [homeassistant.components.template.template_entity] TemplateError('UndefinedError: None has no element 2') while processing template 'Template<template=({{state_attr('weather.le_plessis_mace', 'forecast')[2].condition}}) renders=6>' for attribute '_attr_native_value' in entity 'sensor.weather_condition_2'
2023-10-13 15:28:54.946 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: None has no element 3 when rendering '{{state_attr('weather.le_plessis_mace', 'forecast')[3].temperature}}'
2023-10-13 15:28:54.947 ERROR (MainThread) [homeassistant.components.template.template_entity] TemplateError('UndefinedError: None has no element 3') while processing template 'Template<template=({{state_attr('weather.le_plessis_mace', 'forecast')[3].temperature}}) renders=6>' for attribute '_attr_native_value' in entity 'sensor.weather_temperature_3'
2023-10-13 15:28:54.948 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: None has no element 3 when rendering '{{state_attr('weather.le_plessis_mace', 'forecast')[3].templow}}'
2023-10-13 15:28:54.948 ERROR (MainThread) [homeassistant.components.template.template_entity] TemplateError('UndefinedError: None has no element 3') while processing template 'Template<template=({{state_attr('weather.le_plessis_mace', 'forecast')[3].templow}}) renders=6>' for attribute '_attr_native_value' in entity 'sensor.weather_templow_3'
2023-10-13 15:28:54.948 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: None has no element 3 when rendering '{{state_attr('weather.le_plessis_mace', 'forecast')[3].condition}}'
2023-10-13 15:28:54.962 ERROR (MainThread) [homeassistant.components.template.template_entity] TemplateError('UndefinedError: None has no element 3') while processing template 'Template<template=({{state_attr('weather.le_plessis_mace', 'forecast')[3].condition}}) renders=6>' for attribute '_attr_native_value' in entity 'sensor.weather_condition_3'
2023-10-13 15:28:54.963 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: None has no element 4 when rendering '{{state_attr('weather.le_plessis_mace', 'forecast')[4].temperature}}'
2023-10-13 15:28:54.964 ERROR (MainThread) [homeassistant.components.template.template_entity] TemplateError('UndefinedError: None has no element 4') while processing template 'Template<template=({{state_attr('weather.le_plessis_mace', 'forecast')[4].temperature}}) renders=6>' for attribute '_attr_native_value' in entity 'sensor.weather_temperature_4'
2023-10-13 15:28:54.965 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: None has no element 4 when rendering '{{state_attr('weather.le_plessis_mace', 'forecast')[4].templow}}'
2023-10-13 15:28:54.965 ERROR (MainThread) [homeassistant.components.template.template_entity] TemplateError('UndefinedError: None has no element 4') while processing template 'Template<template=({{state_attr('weather.le_plessis_mace', 'forecast')[4].templow}}) renders=6>' for attribute '_attr_native_value' in entity 'sensor.weather_templow_4'
2023-10-13 15:28:54.966 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: None has no element 4 when rendering '{{state_attr('weather.le_plessis_mace', 'forecast')[4].condition}}'
2023-10-13 15:28:54.967 ERROR (MainThread) [homeassistant.components.template.template_entity] TemplateError('UndefinedError: None has no element 4') while processing template 'Template<template=({{state_attr('weather.le_plessis_mace', 'forecast')[4].condition}}) renders=6>' for attribute '_attr_native_value' in entity 'sensor.weather_condition_4'
2023-10-13 15:28:54.967 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: None has no element 5 when rendering '{{state_attr('weather.le_plessis_mace', 'forecast')[5].temperature}}'
2023-10-13 15:28:54.968 ERROR (MainThread) [homeassistant.components.template.template_entity] TemplateError('UndefinedError: None has no element 5') while processing template 'Template<template=({{state_attr('weather.le_plessis_mace', 'forecast')[5].temperature}}) renders=6>' for attribute '_attr_native_value' in entity 'sensor.weather_temperature_5'
2023-10-13 15:28:54.968 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: None has no element 5 when rendering '{{state_attr('weather.le_plessis_mace', 'forecast')[5].templow}}'
2023-10-13 15:28:54.968 ERROR (MainThread) [homeassistant.components.template.template_entity] TemplateError('UndefinedError: None has no element 5') while processing template 'Template<template=({{state_attr('weather.le_plessis_mace', 'forecast')[5].templow}}) renders=6>' for attribute '_attr_native_value' in entity 'sensor.weather_templow_5'
2023-10-13 15:28:54.971 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: None has no element 5 when rendering '{{state_attr('weather.le_plessis_mace', 'forecast')[5].condition}}'
2023-10-13 15:28:54.971 ERROR (MainThread) [homeassistant.components.template.template_entity] TemplateError('UndefinedError: None has no element 5') while processing template 'Template<template=({{state_attr('weather.le_plessis_mace', 'forecast')[5].condition}}) renders=6>' for attribute '_attr_native_value' in entity 'sensor.weather_condition_5'
2023-10-13 15:28:55.153 DEBUG (MainThread) [homeassistant.components.meteo_france] Finished fetching Météo-France forecast for city Le Plessis-Macé - Pays de la Loire (49) - FR data in 0.159 seconds (success: True)
2023-10-13 15:28:55.166 DEBUG (MainThread) [homeassistant.components.meteo_france] Finished fetching Météo-France rain for city Le Plessis-Macé - Pays de la Loire (49) - FR data in 0.013 seconds (success: True)
2023-10-13 15:28:55.166 DEBUG (MainThread) [homeassistant.components.meteo_france] Department corresponding to Le Plessis-Macé - Pays de la Loire (49) - FR is 49
2023-10-13 15:28:55.196 DEBUG (MainThread) [homeassistant.components.meteo_france] Finished fetching Météo-France alert for department 49 data in 0.030 seconds (success: True)
2023-10-13 15:28:55.198 DEBUG (MainThread) [homeassistant.components.meteo_france.weather] Weather entity (daily) added for Le Plessis-Macé
2023-10-13 15:28:55.235 DEBUG (MainThread) [homeassistant.components.meteo_france] Finished fetching Météo-France forecast for city Le Plessis-Macé - Pays de la Loire (49) - FR data in 0.018 seconds (success: True)
2023-10-13 15:28:55.239 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: 'str object' has no attribute 'weekday' when rendering '{{ ['LUN.', 'MAR.', 'MER.', 'JEU.', 'VEN.', 'SAM.', 'DIM.'][state_attr('weather.le_plessis_mace', 'forecast')[0].datetime.weekday()]}}'
2023-10-13 15:28:55.240 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: 'str object' has no attribute 'weekday' when rendering '{{ ['LUN.', 'MAR.', 'MER.', 'JEU.', 'VEN.', 'SAM.', 'DIM.'][state_attr('weather.le_plessis_mace', 'forecast')[1].datetime.weekday()]}}'
2023-10-13 15:28:55.240 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: 'str object' has no attribute 'weekday' when rendering '{{ ['LUN.', 'MAR.', 'MER.', 'JEU.', 'VEN.', 'SAM.', 'DIM.'][state_attr('weather.le_plessis_mace', 'forecast')[2].datetime.weekday()]}}'
2023-10-13 15:28:55.241 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: 'str object' has no attribute 'weekday' when rendering '{{ ['LUN.', 'MAR.', 'MER.', 'JEU.', 'VEN.', 'SAM.', 'DIM.'][state_attr('weather.le_plessis_mace', 'forecast')[3].datetime.weekday()]}}'
2023-10-13 15:28:55.241 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: 'str object' has no attribute 'weekday' when rendering '{{ ['LUN.', 'MAR.', 'MER.', 'JEU.', 'VEN.', 'SAM.', 'DIM.'][state_attr('weather.le_plessis_mace', 'forecast')[4].datetime.weekday()]}}'
```
Comment puis-je corriger le souci ?

**Comment by NoahJst** [comment]
Bonjour,
Sur cette ligne là :

```yaml
{{ ['LUN.', 'MAR.', 'MER.', 'JEU.', 'VEN.', 'SAM.', 'DIM.'][state_attr('weather.le_plessis_mace', `'forecast')[0].datetime.weekday()]}}
```
Ajoute `|as_datetime`, ça devrait fonctionner :

```yaml
{{ ['LUN.', 'MAR.', 'MER.', 'JEU.', 'VEN.', 'SAM.', 'DIM.'][(state_attr('weather.le_plessis_mace', 'forecast')[0].datetime|as_datetime).weekday()]}}
```

**Comment by lboue** [comment]
Works with this file: https://github.com/lboue/HomeAssistant-Config/blob/sensors.yaml/esphome/config/sensors.yaml
Check PR #2.
